FROM node:20 AS base

ARG GOOGLE_VERTEX_PROJECT
ENV GOOGLE_VERTEX_PROJECT=$GOOGLE_VERTEX_PROJECT

ARG GOOGLE_VERTEX_LOCATION
ENV GOOGLE_VERTEX_LOCATION=$GOOGLE_VERTEX_LOCATION

WORKDIR /app

COPY package*.json ./

COPY . . 

EXPOSE 3000

CMD ["npm", "run", "dev"]
