services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - GOOGLE_VERTEX_PROJECT=boris001
        - GOOGLE_VERTEX_LOCATION=us-central1
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
