[tool.poetry]
name = "agents"
version = "0.1.0"
description = ""
authors = ["Boris Tvaroska <boris@tvaroska.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
jupyterlab = "^4.3.3"
langchain-community = "^0.3.12"
langchain-google-vertexai = "^2.0.9"
google-cloud-aiplatform = "^1.75.0"
openapi-pydantic = "^0.5.0"
langgraph = "^0.2.60"


[tool.poetry.group.dev.dependencies]
langgraph-cli = "^0.1.65"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
