[tool.poetry]
name = "working"
version = "0.1.0"
description = ""
authors = ["Boris Tvaroska <boris@tvaroska.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pgvector = "^0.3.6"
sqlmodel = "^0.0.22"
pydantic = ">=2.9,<2.10"
fastapi = "^0.115.5"
google-cloud-aiplatform = "^1.73.0"
langchain-core = ">=0.3.15,<0.4"
langchain-community = "^0.3.9"
langchain-google-vertexai = "^2.0.8"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.3.1"
ipywidgets = "^8.1.5"
black = "^24.10.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
