[tool.poetry]
name = "working"
version = "0.1.0"
description = ""
authors = ["Boris Tvaroska <boris@tvaroska.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flet = "^0.25.2"
feedparser = "^6.0.11"
tqdm = "^4.67.1"
langchain-core = "^0.3.29"
langchain-google-vertexai = "^2.0.9"
vertexai = "^1.71.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
