[tool.poetry]
name = "article"
version = "0.1.0"
description = ""
authors = ["Boris Tvaroska <boris@tvaroska.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
google-cloud-aiplatform = "^1.73.0"
langchain-core = "^0.3.21"
langchain-google-vertexai = "^2.0.8"
mistune = "^3.0.2"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.3.2"
ipywidgets = "^8.1.5"
tqdm = "^4.67.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
