"""Proactive follow-up scheduler with injectable virtual clock (M1.12).

The scheduler manages durable timers for SLA-driven nudges and escalation, with an
injectable virtual clock for time-warp testing (frontend Theater mode). Timers are
keyed by ``context_id`` (and optionally ``task_id``); the SLA policy (deadline /
cadence / max_nudges) is read from the skill policy (M1.3).

Two-tier architecture (mirroring ledger / disposition / requirements):
- **Pure core** (this module): ``VirtualClock``, ``Timer``, ``TimerKind``,
  ``plan_followups`` (the SLA engine), ``followup_status`` (the read-model).
- **Adapter impl**: ``bridge.adapters.local.scheduler.LocalScheduler`` (in-memory
  timer store implementing the seam over these types).

Exactly-once invariant (docs/lessons-learned.md A7 — CRITICAL):
``due(now)`` marks each returned timer ``fired`` IN PLACE before returning. The
no-duplicate guarantee rides on this invariant — a fired timer NEVER re-appears in
a subsequent ``due()`` call. The ``Timer`` model is a mutable ``@dataclass`` to
permit this in-place mutation (frozen Pydantic would block it).

Deterministic ordering (lessons-learned.md A5):
``due()`` output is sorted by ``(fire_at, sequence, id)`` — no timestamp. The
virtual clock is an integer counter ("ticks"), not a datetime, keeping everything
deterministic and matching the frontend time-warp story.

See:
- wiki/bridge-proactive.md (SLA ladder, overdue → escalated, read-model projection)
- wiki/bridge-seams.md (Scheduler seam)
- docs/lessons-learned.md C1 (address policy: deadline 3 / cadence 2 / max_nudges 2)

Import discipline: imports ``contract`` (if needed) + ``bridge.skills`` (types only)
+ stdlib/Pydantic. Never imports ``agents``, ``seams``, or ``adapters``. Keep this
module OUT of ``bridge/__init__.py`` (preserve cheap ``import bridge`` + the
no-agents-guard clarity).

Note: "Durable" in M1.12 describes the **seam concept** — the local adapter is
in-memory; restart-durability of the timer store is the Sprint-2 GCP adapter (Cloud
Tasks; A7 "deletion is the fired signal"), analogous to the local/Database split for
Sessions/Task-store (M1.2).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Iterable

from pydantic import BaseModel

from bridge.skills import SlaPolicy

__all__ = [
    "VirtualClock",
    "TimerKind",
    "Timer",
    "plan_followups",
    "FollowupState",
    "FollowupStatus",
    "followup_status",
]


class VirtualClock:
    """Injectable virtual clock for time-warp testing.

    Ticks are integers. The clock starts at 0 (or a specified ``start``) and
    advances by integer increments. This matches the SLA policy (``SlaPolicy``
    fields are ``int`` ticks) and keeps everything deterministic.

    Example:
        >>> clock = VirtualClock()
        >>> clock.now()
        0
        >>> clock.advance(3)
        3
        >>> clock.now()
        3
    """

    def __init__(self, start: int = 0) -> None:
        """Initialize the virtual clock.

        Args:
            start: The initial tick value (default 0).
        """
        self._tick = start

    def now(self) -> int:
        """Return the current tick."""
        return self._tick

    def advance(self, ticks: int = 1) -> int:
        """Advance the clock by the given number of ticks.

        Args:
            ticks: Number of ticks to advance (default 1). Must be non-negative.

        Returns:
            The new current tick.

        Raises:
            ValueError: If ticks is negative.
        """
        if ticks < 0:
            raise ValueError(f"Cannot advance by negative ticks: {ticks}")
        self._tick += ticks
        return self._tick


class TimerKind(StrEnum):
    """The two kinds of timers in the SLA ladder."""

    NUDGE = "nudge"
    ESCALATION = "escalation"


@dataclass
class Timer:
    """A scheduled timer (mutable — A7 marks ``fired`` in place).

    The timer is keyed by ``id`` (globally unique, auto-generated by
    ``plan_followups`` as ``{id_prefix}-nudge-{i}`` / ``{id_prefix}-escalation``).
    Timers are scoped to a ``context_id`` (and optionally a ``task_id``).

    The ``fired`` flag is marked ``True`` IN PLACE by ``due(now)`` when the timer
    fires (lessons-learned.md A7 — the exactly-once guarantee rides on this). This
    requires a **mutable** model — hence ``@dataclass``, not a frozen Pydantic model.
    """

    id: str
    context_id: str
    fire_at: int
    kind: TimerKind
    sequence: int = 0  # nudge number (1, 2, ...); 0 for escalation
    task_id: str | None = None
    fired: bool = False


def plan_followups(
    sla: SlaPolicy,
    *,
    start: int,
    context_id: str,
    task_id: str | None = None,
    id_prefix: str | None = None,
) -> list[Timer]:
    """Plan the SLA ladder (nudges + escalation) from a skill policy.

    The SLA ladder (docs/lessons-learned.md C1):
    - **Nudge i** for ``i`` in ``1..max_nudges``:
      ``fire_at = start + deadline + (i-1)*cadence``, ``kind=NUDGE``, ``sequence=i``.
    - **Escalation**: ``fire_at = start + deadline + max_nudges*cadence``,
      ``kind=ESCALATION``, ``sequence=0``.

    For the address policy (``deadline=3, cadence=2, max_nudges=2``) at ``start=0``:
    nudge#1 @ tick 3, nudge#2 @ tick 5, escalation @ tick 7.

    Args:
        sla: The SLA policy (deadline / cadence / max_nudges).
        start: The tick to measure the ladder from (typically the exchange creation time).
        context_id: The exchange ``context_id`` (timers are scoped to the exchange).
        task_id: Optional task ID (for per-task timers).
        id_prefix: Timer ID prefix (defaults to ``context_id``).

    Returns:
        A list of ``Timer`` instances (nudges first, then escalation).

    Example:
        >>> sla = SlaPolicy(deadline=3, cadence=2, max_nudges=2)
        >>> timers = plan_followups(sla, start=0, context_id="ctx-1")
        >>> [(t.kind, t.fire_at, t.sequence) for t in timers]  # doctest: +ELLIPSIS
        [(<TimerKind.NUDGE...>, 3, 1), (<TimerKind.NUDGE...>, 5, 2), ...]
    """
    if id_prefix is None:
        id_prefix = context_id

    timers: list[Timer] = []

    # Nudges: i=1..max_nudges
    for i in range(1, sla.max_nudges + 1):
        fire_at = start + sla.deadline + (i - 1) * sla.cadence
        timer = Timer(
            id=f"{id_prefix}-nudge-{i}",
            context_id=context_id,
            fire_at=fire_at,
            kind=TimerKind.NUDGE,
            sequence=i,
            task_id=task_id,
        )
        timers.append(timer)

    # Escalation
    escalation_fire_at = start + sla.deadline + sla.max_nudges * sla.cadence
    escalation = Timer(
        id=f"{id_prefix}-escalation",
        context_id=context_id,
        fire_at=escalation_fire_at,
        kind=TimerKind.ESCALATION,
        sequence=0,
        task_id=task_id,
    )
    timers.append(escalation)

    return timers


class FollowupState(StrEnum):
    """The three states of the overdue → escalated transition."""

    ON_TRACK = "on_track"  # No nudges fired yet
    OVERDUE = "overdue"  # ≥1 nudge fired, not yet escalated
    ESCALATED = "escalated"  # Escalation timer fired


class FollowupStatus(BaseModel, frozen=True):
    """Read-model projection of the follow-up state for a context.

    This is a **read-model snapshot** (immutable), not a stored record. It is
    computed on-demand by ``followup_status`` over the current timer set.
    """

    context_id: str
    state: FollowupState
    nudges_fired: int
    escalated: bool


def followup_status(timers: Iterable[Timer], *, context_id: str) -> FollowupStatus:
    """Compute the follow-up status read-model for a context.

    The state is derived from the fired timers:
    - If any fired ESCALATION timer → ``ESCALATED``
    - Elif any fired NUDGE timer → ``OVERDUE``
    - Else → ``ON_TRACK``

    ``nudges_fired`` counts fired NUDGE timers; ``escalated`` is ``True`` iff the
    escalation timer fired.

    Args:
        timers: The set of timers to project (typically all timers for the context).
        context_id: The exchange ``context_id`` to filter to.

    Returns:
        A ``FollowupStatus`` snapshot.

    Example:
        >>> timers = [Timer(
        ...     id="t1", context_id="c1", fire_at=3,
        ...     kind=TimerKind.NUDGE, fired=True
        ... )]
        >>> followup_status(timers, context_id="c1")  # doctest: +ELLIPSIS
        FollowupStatus(context_id='c1', state=..., nudges_fired=1, ...)
    """
    # Filter to the context
    context_timers = [t for t in timers if t.context_id == context_id]

    # Count fired timers
    nudges_fired = sum(1 for t in context_timers if t.fired and t.kind == TimerKind.NUDGE)
    escalated = any(t.fired and t.kind == TimerKind.ESCALATION for t in context_timers)

    # Derive state
    if escalated:
        state = FollowupState.ESCALATED
    elif nudges_fired > 0:
        state = FollowupState.OVERDUE
    else:
        state = FollowupState.ON_TRACK

    return FollowupStatus(
        context_id=context_id,
        state=state,
        nudges_fired=nudges_fired,
        escalated=escalated,
    )
